version: '3.8'

services:
  task-manager-fe:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - '${APP_PORT}:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
